### ISSUE TITLE
How to configure without systemd

### ISSUE THREAD

**Issue by peterpt** [cybermaggedon/cyberprobe#1]
Hi , i was compiling your tool on my system but then it stopped , it looks that your tool needs systemd init boot system to work .
My question is :  Who to compile it without systemd ?
My linux does not work with the new systemd implementation .

**Comment by cybermaggedon** [comment]
Hey, thanks for raising the issue, can you try...
```
./configure --with-systemdsystemunitdir=no
```

**Comment by peterpt** [comment]
Thanks , it working like a charm .
however in debian some libraries have different names :
 
Note, selecting 'libexpat1-dev' instead of 'libexpat-dev'
Note, selecting 'liblua5.1-0-dev' instead of 'liblua5.1-dev'
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'

**Comment by peterpt** [comment]
Ok , configure worked fine , but i got some issues on make whe it tries to compile cybermoon-lua.h module :  

`/include/cybermon/cybermon-lua.h: In member function 'void cybermon::lua_state::register_module(const string&, const std::map<std::basic_string<char>, int (*)(lua_State*)>&)':
../include/cybermon/cybermon-lua.h:139:32: error: 'luaL_setfuncs' was not declared in this scope
      luaL_setfuncs(lua, cfns, 0);
                                ^
../include/cybermon/cybermon-lua.h: In member function 'int cybermon::lua_state::raw_len(int)':
../include/cybermon/cybermon-lua.h:302:32: error: 'lua_rawlen' was not declared in this scope
      return lua_rawlen(lua, pos);
                                ^
cybermon-lua.C: In member function 'void cybermon::lua_state::register_table(const std::map<std::basic_string<char>, int (*)(lua_State*)>&)':
cybermon-lua.C:1294:31: error: 'luaL_setfuncs' was not declared in this scope
     luaL_setfuncs(lua, cfns, 0);
                               ^
Makefile:645: recipe for target 'cybermon-lua.lo' failed
` 

any idea ?

**Comment by cybermaggedon** [comment]
Which version of Debian are you using? Do you have Lua 5.2 available to you?

**Comment by cybermaggedon** [comment]
FYI, there is a Debian package on the [releases page](https://github.com/cybermaggedon/cyberprobe/releases)...

If you want to compile yourself, you may be interested in the commands I use to compile for the Debian package which are in these docker files: [development environment](https://github.com/cybermaggedon/cyberprobe-docker/blob/master/Dockerfile.debian.dev) and [compilation](https://github.com/cybermaggedon/cyberprobe-docker/blob/master/Dockerfile.debian.build).

**Comment by peterpt** [comment]
I am using Devuan jessie (non systemd distro) , a fork from debian .
I fixed the issue by installing lua5.2 .
Maybe could be interesting if you could change in README.linux the dependency lua5.1 to lua5.2 , and also add the package libboost-all-dev .
I had to install libboost-all-dev that package even before this module compile error appear .

Thanks for the tip , everything have been compile correctly and tool is working fine .

**Comment by cybermaggedon** [comment]
Ok, will update the README.linux. Thanks for raising this.

**Comment by cybermaggedon** [comment]
README.linux updated using build instructions from dockerfiles, because I know they work.
