### ISSUE TITLE
ERROR RUNNING DB.lua

### ISSUE THREAD

**Issue by 007scorpio** [cybermaggedon/cyberprobe#11]
Exception: Error running script: /etc/cyberprobe/mime.lua:12 module 'mime.core' not found

**Comment by cybermaggedon** [comment]
Thanks for the error report. I'm not sure where /etc/cyberprobe/mime.lua came from - that's not part of anything distributed in the current source code or packages.

I'm guessing that you have a file left there from a previous installation, or your own hacking, so try renaming it out of the way, to see if it works without this file

FYI, my minimal test is...

1) Start ElasticSearch, easier to tidy it up if you run it from a container...
```
docker run -p 9200:9200 elasticsearch
```

2) Run this from cyberprobe source tree...
```
src/cybermon -f tests/samples/smtp.pcap -c config/db.lua
```
