### ISSUE TITLE
cyberprobe configuration file 

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#21]
<control port="8888" username="admin" password="horse_battery_staple">

  
  <interfaces>

    
    <interface name="eth0" filter="not port 10001 and not port 10002"/>

    <-- The delay attribute can be used to specify a delay before
           packets are processed.  In seconds. --> 
    <interface name="eth1" delay="0.5"/>

i find that there is an error when adding this part of the xml.file  other are working

**Comment by hossamsamy007** [comment]
also am using ubuntu 16.04 the interface is

**Comment by cybermaggedon** [comment]
Those should work, what errors are you getting?  The names `eth0` and `eth1` refer to real interfaces.  To see what network interfaces you have on your box, run `ifconfig`on the command line.  You might find the interface is called something like `enp0s3`.

**Comment by hossamsamy007** [comment]
am using ubuntu   ? not  kalilinux  thats why ifconfig    show me
docker0 , enp0s3, lo

**Comment by hossamsamy007** [comment]
oka am with you , but you said eth0 ----------> enp0s3    and what about
eth1 ??

**Comment by cybermaggedon** [comment]
Yeh, looks like you have one interface, enp0s3, so delete the eth1 entry.
