### ISSUE TITLE
while make the cyberprobe project 

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#22]
warning -std=c++11 or -gnu=c++11   how i can solve it ?

**Comment by hossamsamy007** [comment]
make 
make install   that's what i mean ok i found the warning , and what is the preferable environment  for you to build the project am using ubuntu 16.04 is that oka or what  ? and thnx

**Comment by cybermaggedon** [comment]
Hey, thanks for raising warnings, the warnings are benign, but I've fixed them in 952d14401255c660fce17a3299442746479cca29.

**Comment by cybermaggedon** [comment]
We compile on various OSs, but the releases are compiled on Ubuntu 16.04, Debian 8.6, Fedora 26 and CentOS 7.

If you want Ubuntu 16.04 there are packages here...
https://github.com/cybermaggedon/cyberprobe/releases

The packages are built in a GoCD pipeline, so they're always up-to-date.

If you want the compilation commands for a particular OS which are built in containers, you could look at... 
https://github.com/cybermaggedon/cyberprobe-docker
