### ISSUE TITLE
socket binding 

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#23]
etsi-rcvr 10000 | tcpdump -n -r -
reading from file -, link-type RAW (Raw IP)
Exception: Socket bind failed.

how can i solve it  and what is -n -r refere to 

the configuration file is c.xml 
<?xml version="1.0" encoding="ISO-8859-1"?>

<configuration>

  <interfaces>
    <interface name="enp0s3"/>
  </interfaces>

 <targets>
  <target address="192.168.1.101/24" liid="123456"/>
</targets>

  <endpoints>
  </endpoints>

</configuration>

**Comment by cybermaggedon** [comment]
Appears to indicate that TCP port 10000 is in use on your machine.

Try `netstat -an | grep LISTEN` which will show you what's in use.  If port 10000 is in use, try a different port number e.g. 9000.  The port number is referred to in `c.xml` too.
