### ISSUE TITLE
is cyberprobe SIEM ?

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#25]
iwant to know can we use cyberprobe as SIEM and ifnot  are you going to intergrate the plugins of the SIEM  project into cyberprobe and how can i use it as SIEM project in my company or anything else ?

**Comment by cybermaggedon** [comment]
Cyberprobe plus ElasticSearch gives you a good network workflow and forensic view of data on the network.

When you say SIEM, I guess you have in mind things like plugging into a threat exchange, reporting on vulnerabilities and incident response?  Some of that can be done with cyberprobe in a wider ecosystem of tools, but I don't have the code in open source at the moment.

OSSIM is the best open-source SIEM at the moment IMHO, you have to pay for USIM to get all the rich features.
