### ISSUE TITLE
new error at new cybprobe 

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#26]
cybermon -p 10000 -c /usr/local/etc/cyberprobe/db.lua 
Segmentation fault (core dumped)

**Comment by cybermaggedon** [comment]
That's strange... can you see if you can get a stack trace out of it?

Command `gdb /usr/local/bin/cybermon` and then `run -p 10000 -c /usr/local/src/cyberprobe/db.lua`

When you get a segmentation fault, try `where` to get a stack trace.

**Comment by hossamsamy007** [comment]
gdb /usr/local/bin/cybermo
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
/usr/local/bin/cybermo: No such file or directory.
(gdb) 


--------------------------------------------------------------------------
cybermon  -p 10000 -c /usr/local/src/cyberprobe/db.lua
Segmentation fault (core dumped)

**Comment by hossamsamy007** [comment]
gdb /usr/local/bin/cybermon 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/cybermon...done.
(gdb)

**Comment by hossamsamy007** [comment]
the same result error : 
cybermon -p 10000 -c /usr/local/src/cyberprobe/db.lua
Segmentation fault (core dumped)

**Comment by cybermaggedon** [comment]
gdb is a debugger, and and can be used to get a stacktrace of the failure.  You got it up and running, the next two steps are...

- Type `run -p 10000 -c /usr/local/src/cyberprobe/db.lua` which starts cybermon
- When it crashes, you can type `where` to get a stacktrace.

Which operating system / Linux version are you running on?

**Comment by hossamsamy007** [comment]
the same result error : 
cybermon -p 10000 -c /usr/local/src/cyberprobe/db.lua
Segmentation fault (core dumped)

**Comment by cybermaggedon** [comment]
Hey, guess I'm not explaining myself very well.  It would help if you could get a stack trace out of cyberprobe so that I know what the problem is.

To do this...

- Run gdb on cybermon: `gdb /usr/local/bin/cybermon`
- Once you're in the debugger, start cybermon thus: `run -p 10000 -c /usr/local/src/cyberprobe/db.lua`
- When it crashes, type the command `where` and send me the output.

That way, I'll get an idea where the problem is.

If you're using a supported operating system, you might get better results by using one of the 'release' packages... https://github.com/cybermaggedon/cyberprobe/releases

**Comment by cybermaggedon** [comment]
Opened a discussion forum if you want to discuss this further...
https://groups.google.com/d/forum/cyberprobe-discussion
