### ISSUE TITLE
cybermon-elasticsearch  1.6.8

### ISSUE THREAD

**Issue by hossamsamy007** [cybermaggedon/cyberprobe#27]
cybermon-elasticsearch
elasticsearch: Exception: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: //cyberprobe (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7cc5ddab50>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/bin/cybermon-elasticsearch", line 204, in <module>
    init()
  File "/usr/local/bin/cybermon-elasticsearch", line 94, in init
    time.sleep(1)
NameError: global name 'time' is not defined

**Comment by cybermaggedon** [comment]
That indicates that elasticsearch isn't running.

When that happens, it goes into a retry loop, and you then see the time error, which I've fixed in 2863da551f7552efa049ba1f8c7b2ba0fd28fe50.
